import { User, Product, Order, LearningModule, SupportTicket, Review } from '../src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-artisan-1',
    name: 'Vedant Mishra',
    email: 'vedant.mishra@gramai.in',
    role: 'entrepreneur',
    phone: '+91 94310 44521',
    location: 'Varanasi Craft & Tech Hub',
    state: 'Uttar Pradesh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    bio: 'Founder & Lead Engineer at Gram AI. Integrating Core Computer Science & Engineering (AOA, DBMS, Applied MATHS, OOP) with grassroots rural commerce to ensure 86%+ direct UPI payouts for Indian artisans.',
    shgName: 'Mishra Rural Guild & Tech Labs',
    joinedDate: '2024-01-01'
  },
  {
    id: 'user-artisan-2',
    name: 'Rameshwar Rathore',
    email: 'rameshwar@gramai.org',
    role: 'entrepreneur',
    phone: '+91 94140 23411',
    location: 'Molela Village, Rajsamand',
    state: 'Rajasthan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    bio: 'Fourth generation terracotta craftsman specializing in organic earthenware, clay cooking handis, and terracotta water coolers.',
    shgName: 'Mitti Shilp Samiti',
    joinedDate: '2024-01-18'
  },
  {
    id: 'user-customer-1',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@example.com',
    role: 'customer',
    phone: '+91 98112 34567',
    location: 'Indiranagar, Bengaluru',
    state: 'Karnataka',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    bio: 'Eco-conscious design enthusiast passionate about supporting direct rural artisanal communities.',
    joinedDate: '2024-05-10'
  },
  {
    id: 'user-admin-1',
    name: 'Pooja Venkatesh',
    email: 'pooja.admin@gramai.org',
    role: 'admin',
    phone: '+91 98450 11223',
    location: 'Regional Hub HQ, Patna',
    state: 'Bihar',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    bio: 'Gram AI Village Cluster Development Officer & Quality Assurance Lead.',
    joinedDate: '2023-11-01'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    artisanId: 'user-artisan-1',
    artisanName: 'Vedant Mishra (Mishra Craft Guild)',
    artisanLocation: 'Varanasi, Uttar Pradesh',
    title: 'Hand-Painted Madhubani Tussar Silk Dupatta',
    category: 'textiles',
    price: 1850,
    originalPrice: 2400,
    stock: 14,
    unit: 'piece',
    rating: 4.9,
    reviewsCount: 38,
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    description: 'Exquisite 100% natural Tussar silk dupatta featuring authentic Kohbar and peacock motifs painstakingly hand-painted using natural vegetable dyes, twig brushes, and nib pens.',
    artisanStory: 'Curated by Vedant Mishra, combining generational artisan craftsmanship with algorithmic logistics and transparent database accounting to eliminate middlemen and empower rural creators.',
    materials: ['Pure Tussar Silk', 'Natural Indigo', 'Turmeric Pigments', 'Lampblack'],
    inStock: true,
    featured: true,
    fairTradePercent: 86
  },
  {
    id: 'prod-2',
    artisanId: 'user-artisan-2',
    artisanName: 'Rameshwar Rathore',
    artisanLocation: 'Molela, Rajasthan',
    title: 'Handcrafted Terracotta Clay Biryani & Curd Pot (2.5L)',
    category: 'pottery',
    price: 680,
    originalPrice: 850,
    stock: 22,
    unit: 'pot with lid',
    rating: 4.8,
    reviewsCount: 52,
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    description: 'Naturally unglazed, kiln-baked traditional clay handi. Enriches food with calcium, magnesium, and natural earthy aroma while ensuring non-toxic, slow alkaline cooking.',
    artisanStory: 'Rameshwar sources clay from the local riverbed of Banas. Each pot is hand-turned on a wooden potter wheel and seasoned with natural rice starch before firing.',
    materials: ['Organic Banas River Clay', 'Mica flakes', 'Rice starch seasoning'],
    inStock: true,
    featured: true,
    fairTradePercent: 88
  },
  {
    id: 'prod-3',
    artisanId: 'user-artisan-3',
    artisanName: 'Vasantha Rao & Co-op',
    artisanLocation: 'Wayanad, Kerala',
    title: 'Wayanad High-Curcumin Raw Organic Turmeric (500g)',
    category: 'spices',
    price: 340,
    originalPrice: 420,
    stock: 45,
    unit: '500g pack',
    rating: 5.0,
    reviewsCount: 64,
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    description: 'Certified organic, solar sun-dried heirloom turmeric powder with over 6.2% verified lab curcumin content. Grown in shade under Western Ghats canopy without chemical inputs.',
    artisanStory: 'A collective of 40 tribal farmers in Wayanad practicing zero-budget natural farming. Gram AI guarantees direct farm-gate collection with immediate UPI payment.',
    materials: ['100% Curcuma Longa', 'Zero preservatives', 'Non-irradiated'],
    inStock: true,
    featured: true,
    fairTradePercent: 84
  },
  {
    id: 'prod-4',
    artisanId: 'user-artisan-4',
    artisanName: 'Biren Mondal',
    artisanLocation: 'Sundarbans Biosphere, West Bengal',
    title: 'Wild Mangrove Raw Forest Honey (400g Glass Jar)',
    category: 'honey_oils',
    price: 520,
    originalPrice: 650,
    stock: 19,
    unit: '400g jar',
    rating: 4.9,
    reviewsCount: 29,
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    description: 'Unprocessed, unfiltered multi-floral raw nectar harvested sustainably by traditional Mouli foragers from wild Apis dorsata honeycombs in coastal mangrove forests.',
    artisanStory: 'Mouli honey-gatherers face extreme challenges in the delta. Direct selling enables safety insurance funds, eco-friendly protective gear, and living wages for 15 families.',
    materials: ['Pure Wild Mangrove Nectar', 'Natural pollen grains', 'Raw & Unpasteurized'],
    inStock: true,
    featured: false,
    fairTradePercent: 82
  },
  {
    id: 'prod-5',
    artisanId: 'user-artisan-5',
    artisanName: 'Hemant Boro',
    artisanLocation: 'Barpeta, Assam',
    title: 'Woven Golden Bamboo Storage Basket with Lid',
    category: 'bamboo_wood',
    price: 790,
    originalPrice: 990,
    stock: 16,
    unit: 'piece',
    rating: 4.7,
    reviewsCount: 21,
    imageUrl: 'https://images.unsplash.com/photo-1595079672139-5470805087e2?auto=format&fit=crop&w=800&q=80',
    description: 'Fine split-cane bamboo basket intricately hand-woven with interlocking geometric lattice. Treated naturally against wood-borers using smoked sal leaves.',
    artisanStory: 'Bamboo craft is an indigenous heritage of the Bodo community. Gram AI logistics has opened metro gifting and decor markets across Mumbai and Bangalore.',
    materials: ['Seasoned Assam Golden Bamboo', 'Natural vegetable polish'],
    inStock: true,
    featured: true,
    fairTradePercent: 87
  },
  {
    id: 'prod-6',
    artisanId: 'user-artisan-6',
    artisanName: 'Santosh Devi (Kutch Weavers)',
    artisanLocation: 'Bhuj, Gujarat',
    title: 'Kutch Kala Cotton Handwoven Throw Blanket',
    category: 'textiles',
    price: 2100,
    originalPrice: 2600,
    stock: 9,
    unit: 'piece (60x80 in)',
    rating: 5.0,
    reviewsCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1606744824163-985d376605aa?auto=format&fit=crop&w=800&q=80',
    description: 'Rain-fed indigenous Kala cotton woven on pit-looms with organic plant-based madder root and indigo dyes. Breathable, durable, and gets softer with every wash.',
    artisanStory: 'Kala cotton requires zero chemical fertilizers or synthetic pesticides. It supports local dryland pastoralists and weaver families in the arid Rann of Kutch.',
    materials: ['100% Rainfed Kala Cotton', 'Madder Root', 'Natural Indigo'],
    inStock: true,
    featured: false,
    fairTradePercent: 85
  },
  {
    id: 'prod-7',
    artisanId: 'user-artisan-7',
    artisanName: 'Maniram Gurjar',
    artisanLocation: 'Alwar, Rajasthan',
    title: 'Cold-Pressed Wood-Ghani Mustard Oil (1 Litre)',
    category: 'honey_oils',
    price: 290,
    originalPrice: 350,
    stock: 35,
    unit: '1L glass bottle',
    rating: 4.9,
    reviewsCount: 47,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
    description: 'Extracted slowly at room temperature using a traditional bull-driven wooden pestle (Kachi Ghani). Retains all natural pungency, antioxidants, and Omega-3 fatty acids.',
    artisanStory: 'Smallholder farmers in Mewat region cooperative. No chemical refining, no bleaching, no artificial flavoring — pure farm-fresh culinary heritage.',
    materials: ['100% Pure Black Mustard Seeds', 'Single cold press'],
    inStock: true,
    featured: false,
    fairTradePercent: 89
  },
  {
    id: 'prod-8',
    artisanId: 'user-artisan-8',
    artisanName: 'Nagaswamy Gowda',
    artisanLocation: 'Channapatna, Karnataka',
    title: 'Non-Toxic Vegetable Lacquer Wooden Balancing Game',
    category: 'bamboo_wood',
    price: 640,
    originalPrice: 799,
    stock: 25,
    unit: 'set of 12 blocks',
    rating: 4.8,
    reviewsCount: 33,
    imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80',
    description: 'Hand-turned Ivory Wood (Wrightia tinctoria) coated with natural tree resin lacquer mixed with turmeric, kumkum, and indigo colors. 100% child-safe and biodegradable.',
    artisanStory: 'Channapatna toy craft dates back to Tipu Sultan. Gram AI helps generational artisans compete with imported plastic toys by celebrating non-toxic sustainability.',
    materials: ['Sustainably Harvested Hale Wood', 'Natural Shellac', 'Food-grade vegetable tints'],
    inStock: true,
    featured: true,
    fairTradePercent: 83
  },
  {
    id: 'prod-9',
    artisanId: 'user-artisan-9',
    artisanName: 'Ghulam Mohammad & Family',
    artisanLocation: 'Pampore, Jammu & Kashmir',
    title: 'GI-Certified Grade A1 Kashmiri Mongra Saffron (1g)',
    category: 'spices',
    price: 650,
    originalPrice: 850,
    stock: 30,
    unit: '1g sealed glass vial',
    rating: 5.0,
    reviewsCount: 58,
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    description: 'Certified 100% pure Kashmiri Mongra saffron stigmas harvested from Karewa highland fields. Features intense deep crimson filaments, unparalleled natural safranal aroma, and zero chemical dyeing.',
    artisanStory: 'Ghulam Mohammad represents a 5-generation saffron-cultivating clan in Pampore. Gram AI provides direct moisture-proof tamper testing and direct consumer remittance.',
    materials: ['100% Crocus Sativus Stigmas', 'Natural Mongra Grade A1'],
    inStock: true,
    featured: true,
    fairTradePercent: 88
  },
  {
    id: 'prod-10',
    artisanId: 'user-artisan-10',
    artisanName: 'Kailash Chand Kripal',
    artisanLocation: 'Kot Jewar, Jaipur, Rajasthan',
    title: 'Jaipur Traditional Blue Pottery Floral Ceramic Vase (8 inch)',
    category: 'pottery',
    price: 920,
    originalPrice: 1200,
    stock: 18,
    unit: 'piece',
    rating: 4.9,
    reviewsCount: 36,
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    description: 'Handcrafted Egyptian paste ceramic made without clay, utilizing quartz stone powder, powdered glass, Fuller earth, and gum. Painted with Persian cobalt blue floral arabesques and low-fired in wood kilns.',
    artisanStory: 'Kailash preserved this GI-recognized craft from fading during industrial ceramic shifts. Direct export orders through Gram AI have allowed him to train 12 village youths.',
    materials: ['Quartz Powder', 'Cobalt Oxide', 'Glass Powder', 'Natural Gum'],
    inStock: true,
    featured: true,
    fairTradePercent: 87
  },
  {
    id: 'prod-11',
    artisanId: 'user-artisan-11',
    artisanName: 'Baburao Shinde Leather Guild',
    artisanLocation: 'Athani & Kolhapur, Maharashtra',
    title: 'Authentic Vegetable-Tanned Kolhapuri Leather Chappals',
    category: 'bamboo_wood',
    price: 1350,
    originalPrice: 1750,
    stock: 20,
    unit: 'pair',
    rating: 4.8,
    reviewsCount: 41,
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    description: 'Generational handcrafted open-toed sandals made using vegetable-tanned buffalo leather treated with babul bark and myrobalan nuts. Hand-braided with leather cord and natural castor oil conditioning.',
    artisanStory: 'The Kolhapur leather artisans formed a direct co-op on Gram AI to eliminate distributor chains that forced artisans to sell at heavy discounts.',
    materials: ['Vegetable-Tanned Leather', 'Babul Bark Tanning', 'Castor Oil Finish'],
    inStock: true,
    featured: false,
    fairTradePercent: 86
  },
  {
    id: 'prod-12',
    artisanId: 'user-artisan-12',
    artisanName: 'Bopaiah & Tribal Forest Foragers',
    artisanLocation: 'Madikeri, Coorg, Karnataka',
    title: 'Shade-Grown Estate Arabica Coffee Beans (Dark Roast 250g)',
    category: 'spices',
    price: 440,
    originalPrice: 550,
    stock: 35,
    unit: '250g valve pouch',
    rating: 5.0,
    reviewsCount: 52,
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
    description: 'Sustainably cultivated under native evergreen forest canopies alongside wild cardamom and black pepper. Slow-roasted in small batches for distinct notes of dark chocolate, nutmeg, and caramelized fig.',
    artisanStory: 'Bopaiah works with small tribal plantation holders in Coorg. Gram AI enables single-origin freshness delivered within 4 days of roasting.',
    materials: ['100% Single Origin Arabica Beans', 'Slow Drum Roast'],
    inStock: true,
    featured: true,
    fairTradePercent: 85
  },
  {
    id: 'prod-13',
    artisanId: 'user-artisan-13',
    artisanName: 'Budhram Mandavi (Gadhwa Art)',
    artisanLocation: 'Kondagaon, Bastar, Chhattisgarh',
    title: 'Bastar Tribal Lost-Wax Cast Bell Metal Nandi Figurine',
    category: 'bamboo_wood',
    price: 1650,
    originalPrice: 2100,
    stock: 12,
    unit: 'piece (6 inch)',
    rating: 4.9,
    reviewsCount: 27,
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    description: 'Ancient 4,000-year-old Dokra metal casting process using beeswax threads, riverbed clay cores, and molten scrap brass. No two pieces are ever identical.',
    artisanStory: 'Budhram leads an indigenous artisan collective in Bastar. With direct Gram AI logistics, his fragile metal craft reaches galleries and design homes safely.',
    materials: ['Bell Metal Brass', 'Natural Beeswax Mould', 'River Clay'],
    inStock: true,
    featured: false,
    fairTradePercent: 87
  },
  {
    id: 'prod-14',
    artisanId: 'user-artisan-14',
    artisanName: 'Varalakshmi Handlooms',
    artisanLocation: 'Pedana, Machilipatnam, Andhra Pradesh',
    title: 'Machilipatnam Kalamkari Hand-Block Printed Cotton Saree',
    category: 'textiles',
    price: 2450,
    originalPrice: 3200,
    stock: 15,
    unit: 'saree with blouse piece',
    rating: 4.9,
    reviewsCount: 39,
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    description: '100% fine count cotton hand-block printed using hand-carved teak wood blocks and natural vegetable dyes (pomegranate rind, madder, alum). Washed in flowing canal waters for color fastness.',
    artisanStory: 'Varalakshmi heads a 22-woman weaving group reviving forgotten traditional floral jaal motifs and receiving fair monthly payments directly into their accounts.',
    materials: ['Pure Breathable Cotton', 'Pomegranate Rind', 'Natural Madder', 'Alum Mordant'],
    inStock: true,
    featured: true,
    fairTradePercent: 86
  },
  // CLOTHES CATEGORY
  {
    id: 'prod-clothes-1',
    artisanId: 'user-artisan-1',
    artisanName: 'Vedant Mishra (Mishra Craft Guild)',
    artisanLocation: 'Varanasi, Uttar Pradesh',
    title: 'Hand-Tailored Varanasi Khadi Cotton Kurta & Trousers Set',
    category: 'clothes',
    price: 1550,
    originalPrice: 1999,
    stock: 24,
    unit: 'kurta & trouser set',
    rating: 4.9,
    reviewsCount: 44,
    imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
    description: '100% handspun Khadi cotton tailored for all-day breathability and comfort. Hand-loomed in Varanasi village clusters with shell buttons and contrast piping.',
    artisanStory: 'Crafted under the direction of Vedant Mishra by rural handloom weavers in Varanasi. Every garment sold provides 86% direct payment to artisan families.',
    materials: ['Handspun Khadi Cotton', 'Natural Mother-of-Pearl Shell Buttons'],
    inStock: true,
    featured: true,
    fairTradePercent: 86
  },
  {
    id: 'prod-clothes-2',
    artisanId: 'user-artisan-6',
    artisanName: 'Santosh Devi & Kutch Guild',
    artisanLocation: 'Dhamadka, Kutch, Gujarat',
    title: 'Ajrakh Hand-Block Printed Cotton Shirt & Ethnic Top',
    category: 'clothes',
    price: 1250,
    originalPrice: 1650,
    stock: 18,
    unit: 'piece',
    rating: 4.8,
    reviewsCount: 31,
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    description: '16-step traditional Ajrakh resist block printing using natural indigo, harda, and iron rust minerals on 100% fine cotton fabric.',
    artisanStory: 'Sustains a 400-year-old riverbank printing heritage in Kutch with guaranteed living wages and zero-chemical runoff.',
    materials: ['Pure Cambric Cotton', 'Natural Harda', 'Natural Indigo'],
    inStock: true,
    featured: false,
    fairTradePercent: 87
  },
  // SPORTS CATEGORY
  {
    id: 'prod-sports-1',
    artisanId: 'user-artisan-15',
    artisanName: 'Bashir Ahmad & Sons Willow Works',
    artisanLocation: 'Bijbehara, Anantnag, Jammu & Kashmir',
    title: 'Handcrafted Kashmir Willow Cricket Bat (Grade-1 Pro Willow)',
    category: 'sports',
    price: 1890,
    originalPrice: 2490,
    stock: 22,
    unit: 'full-size cricket bat',
    rating: 5.0,
    reviewsCount: 67,
    imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b10554f03?auto=format&fit=crop&w=800&q=80',
    description: 'Genuine air-seasoned Kashmir willow handcrafted along the Jhelum valley. Features 6+ straight grains, pronounced convex spine, lightweight balance, and Singapore cane 3-piece handle.',
    artisanStory: 'Crafted by generational bat-makers whose craft was squeezed by commercial middlemen. Gram AI brings verified direct factory pricing to budding athletes and sports clubs nationwide.',
    materials: ['Selected Grade-1 Kashmir Willow', 'Singapore Cane Handle', 'Rubber Chevron Grip'],
    inStock: true,
    featured: true,
    fairTradePercent: 88
  },
  {
    id: 'prod-sports-2',
    artisanId: 'user-artisan-16',
    artisanName: 'Kaveri Natural Sports Co-op',
    artisanLocation: 'Alappuzha, Kerala',
    title: 'Natural Rubber & Organic Jute Anti-Slip Yoga Mat (6mm Extra Cushion)',
    category: 'sports',
    price: 1150,
    originalPrice: 1550,
    stock: 28,
    unit: 'mat with cotton sling strap',
    rating: 4.9,
    reviewsCount: 42,
    imageUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80',
    description: 'Eco-friendly workout and yoga mat engineered from sustainable coastal jute fibers bonded to textured tree rubber. Free of PVC, toxic glues, and chemical phthalates.',
    artisanStory: 'Provides clean livelihood opportunities for 35 coastal women coir workers, blending ancient wellness materials with modern fitness durability.',
    materials: ['Natural Tree Rubber', 'Organic Woven Jute Fiber', 'Biodegradable Cotton'],
    inStock: true,
    featured: true,
    fairTradePercent: 85
  },
  {
    id: 'prod-sports-3',
    artisanId: 'user-artisan-17',
    artisanName: 'Suraj Woodworks Collective',
    artisanLocation: 'Meerut, Uttar Pradesh',
    title: 'Solid Sheesham Wood Championship Carrom Board with Coins (32-Inch)',
    category: 'sports',
    price: 2400,
    originalPrice: 3200,
    stock: 14,
    unit: 'board with wooden coins & striker',
    rating: 4.8,
    reviewsCount: 35,
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    description: 'Tournament grade heavy Sheesham wood border (3x2 inch) with super-smooth French polished English Birch ply playing surface for lightning rebound speed.',
    artisanStory: 'Crafted in Meerut cottage workshops famous for sports carpentry. Sold directly to gaming enthusiasts with shock-absorbent eco-packaging.',
    materials: ['Solid Sheesham Wood Border', 'Smooth Birch Ply', 'Handmade Wood Coins'],
    inStock: true,
    featured: false,
    fairTradePercent: 86
  },
  // RATION & GROCERIES CATEGORY
  {
    id: 'prod-ration-1',
    artisanId: 'user-artisan-18',
    artisanName: 'Chambal Kisan SHG & Farmers',
    artisanLocation: 'Sehore, Madhya Pradesh',
    title: 'Stone-Ground Sharbati Whole Wheat Atta & Desi Chana Dal (5kg Ration Kit)',
    category: 'ration',
    price: 490,
    originalPrice: 620,
    stock: 50,
    unit: '5kg pack (3kg Atta + 2kg Dal)',
    rating: 5.0,
    reviewsCount: 82,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    description: 'Chakki stone-ground whole wheat atta with 100% natural wheat germ and bran retained, coupled with unpolished desi chana dal for daily wholesome nutrition.',
    artisanStory: 'Direct from Sehore organic farmer cluster practicing zero chemical cultivation. Tested for zero synthetic fertilizers and pesticide residues.',
    materials: ['MP Sharbati Whole Wheat', 'Unpolished Desi Chana Dal', 'Zero Preservatives'],
    inStock: true,
    featured: true,
    fairTradePercent: 87
  },
  {
    id: 'prod-ration-2',
    artisanId: 'user-artisan-19',
    artisanName: 'Doon Organic Farmers Guild',
    artisanLocation: 'Dehradun Valley, Uttarakhand',
    title: 'Traditional Dehradun Basmati Rice & Organic Foxtail Millets (2kg Ration Pack)',
    category: 'ration',
    price: 380,
    originalPrice: 480,
    stock: 40,
    unit: '2kg pack',
    rating: 4.9,
    reviewsCount: 56,
    imageUrl: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=800&q=80',
    description: 'Naturally aged, extra-long grain Himalayan Basmati rice irrigated with glacial mountain runoff, paired with nutrient-dense, gluten-free Foxtail millet (Kangni).',
    artisanStory: 'Small mountain farmers preserving indigenous seed varieties. Farm-gate collection with direct digital payments via Gram AI ledger.',
    materials: ['Aged Dehradun Basmati Rice', 'Organic Foxtail Millet (Kangni)'],
    inStock: true,
    featured: true,
    fairTradePercent: 86
  },
  {
    id: 'prod-ration-3',
    artisanId: 'user-artisan-20',
    artisanName: 'Bansi Gir Goshala & Oil Mill',
    artisanLocation: 'Junagadh, Gujarat',
    title: 'Desi Gir Cow A2 Bilona Ghee & Cold-Pressed Sesame Oil (1L Kitchen Duo)',
    category: 'ration',
    price: 1350,
    originalPrice: 1750,
    stock: 25,
    unit: '1L duo (500ml Ghee + 500ml Oil)',
    rating: 5.0,
    reviewsCount: 71,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    description: 'Vedic bilona churned A2 cultured butter ghee from grass-fed indigenous Gir cows, paired with slow wood-pressed unrefined black sesame (til) oil.',
    artisanStory: 'Supports ethical native cow preservation and traditional bull-driven wooden ghani pressing in Saurashtra villages.',
    materials: ['Pure A2 Gir Cow Milk Butter', 'Cold-Pressed Sesame Seeds'],
    inStock: true,
    featured: false,
    fairTradePercent: 89
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-901',
    trackingId: 'GRAM-88219',
    customerId: 'user-customer-1',
    customerName: 'Arjun Sharma',
    customerPhone: '+91 98112 34567',
    shippingAddress: '42, 12th Main, 4th Cross, Indiranagar, Bengaluru, KA 560038',
    items: [
      {
        productId: 'prod-1',
        title: 'Hand-Painted Madhubani Tussar Silk Dupatta',
        price: 1850,
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        artisanName: 'Vedant Mishra'
      },
      {
        productId: 'prod-3',
        title: 'Wayanad High-Curcumin Raw Organic Turmeric (500g)',
        price: 340,
        quantity: 2,
        imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
        artisanName: 'Vasantha Rao'
      }
    ],
    totalAmount: 2530,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    upiRefId: 'UPI-AXIS-992817462',
    orderStatus: 'out_for_delivery',
    createdAt: '2026-09-24T14:20:00Z',
    deliveryDateEstimated: '2026-09-28',
    currentHub: 'Bengaluru East Distribution Hub, Indiranagar',
    deliveryPartner: 'Gram Express & India Post Nodal',
    deliveryAgentPhone: '+91 99001 84210 (Rajesh Kumar)',
    deliveryOtp: '4829'
  },
  {
    id: 'ORD-2026-894',
    trackingId: 'GRAM-77401',
    customerId: 'user-customer-1',
    customerName: 'Arjun Sharma',
    customerPhone: '+91 98112 34567',
    shippingAddress: '42, 12th Main, Indiranagar, Bengaluru, KA 560038',
    items: [
      {
        productId: 'prod-2',
        title: 'Handcrafted Terracotta Clay Biryani Pot',
        price: 680,
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        artisanName: 'Rameshwar Rathore'
      }
    ],
    totalAmount: 680,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    upiRefId: 'UPI-HDFC-33109482',
    orderStatus: 'delivered',
    createdAt: '2026-09-15T09:12:00Z',
    deliveryDateEstimated: '2026-09-19',
    currentHub: 'Delivered to Doorstep',
    deliveryPartner: 'Gram Express',
    deliveryAgentPhone: '+91 98822 10992',
    deliveryOtp: '1109'
  }
];

export const INITIAL_LEARNING_MODULES: LearningModule[] = [
  {
    id: 'learn-1',
    title: 'Zero-Waste Packaging for Fragile Clay & Glass Goods',
    category: 'packaging',
    duration: '14 mins',
    language: 'Hindi & Regional',
    level: 'Beginner',
    summary: 'Learn how to replace expensive plastic bubble wraps with discarded dried banana fibre, rice husk cushions, and corrugated honeycomb sleeves.',
    keyPoints: [
      'Layering shock absorption using local organic agricultural by-products',
      'Drop-test verification from 4 feet without breakage',
      'Weight optimization to lower inter-state freight courier rates by 22%',
      'Cost comparison: ₹4 per item with agro-cushion vs ₹18 with plastic'
    ],
    audioScript: 'Namaste artisans! Today we will learn how to package fragile pottery and glass jars safely for courier delivery without spending extra money on plastic bubble wraps. Agricultural waste like rice husks and shredded jute can absorb heavy shocks...',
    instructor: 'Shrikant Patil (Gram Rural Logistics Lead)',
    icon: 'PackageCheck'
  },
  {
    id: 'learn-2',
    title: 'Govt Schemes 2026: PM Mudra & PM Vishwakarma Subsidy',
    category: 'schemes',
    duration: '18 mins',
    language: 'Multilingual',
    level: 'Beginner',
    summary: 'Complete guide to accessing collateral-free working capital loans up to ₹3,00,000 at 5% subsidized interest under the PM Vishwakarma scheme.',
    keyPoints: [
      'Who qualifies: Traditional potters, weavers, carpenters, blacksmiths',
      'Required documents: Aadhaar card, Village Sarpanch/Panchayat certificate',
      'Direct toolkit incentive of ₹15,000 credit directly to bank account',
      'Step-by-step assistance through Gram AI nodal kiosks'
    ],
    audioScript: 'Hello friends! Many village entrepreneurs miss out on government capital subsidies because of paperwork fears. Let us break down how to get your PM Vishwakarma certificate in three simple steps...',
    schemeBenefit: 'Up to ₹3 Lakh Collateral-Free Credit + ₹15,000 Free Modern Toolkit Grant',
    instructor: 'Anjali Deshmukh (Microfinance Counselor)',
    icon: 'Landmark'
  },
  {
    id: 'learn-3',
    title: 'Direct UPI & Digital Ledger for Self-Help Groups (SHGs)',
    category: 'finance',
    duration: '12 mins',
    language: 'Hindi & Tamil',
    level: 'Beginner',
    summary: 'How SHG treasurers can manage transparent digital cashbooks, QR code collections, and direct split payouts without bank queues.',
    keyPoints: [
      'Setting up unified village SHG merchant QR code with zero MDR fee',
      'Daily automated SMS voice alerts in local tongue upon customer payment',
      'Automated member dividend split ledger calculation',
      'Preventing common digital payment fraud and fake screenshot scams'
    ],
    audioScript: 'In this session, we show how your Mahila Bachat Gat can accept digital UPI payments directly from urban buyers. Every rupee is credited instantly to your SHG bank account with zero middleman deduction...',
    instructor: 'Sunita Devi (Lead Artisan & SHG Trainer)',
    icon: 'CreditCard'
  },
  {
    id: 'learn-4',
    title: 'Export Readiness: Lab Testing & FSSAI / Handloom Mark',
    category: 'quality',
    duration: '22 mins',
    language: 'English & Hindi',
    level: 'Intermediate',
    summary: 'Standards required to sell organic spices, wild honey, and natural silks to international premium buyers in Europe and North America.',
    keyPoints: [
      'FSSAI Organic and pesticide residue compliance testing steps',
      'Geographical Indication (GI) tag authentication certificate process',
      'Moisture control for spices and honey to prevent mold during maritime transit',
      'Creating barcode labels that tell your village origin story'
    ],
    audioScript: 'International conscious consumers are hungry for pure, unadulterated village spices. But export requires strict pesticide residue tests. Here is how Gram AI aggregates testing to lower individual certification costs...',
    instructor: 'Dr. K. Ramanathan (Agri-Commodity Certification Specialist)',
    icon: 'Award'
  },
  {
    id: 'learn-aoa',
    title: 'AOA: Algorithm Design in Rural Logistics & Knapsack Routing',
    category: 'aoa_algorithms',
    duration: '22 mins',
    language: 'Multilingual (18+ Languages)',
    level: 'Core Engineering',
    summary: 'Deep dive into how Dijkstra & Bellman-Ford O((V+E) log V) algorithms optimize parcel routing across India Post 154,000 branch hubs, plus 0/1 Knapsack DP for vehicle packing.',
    keyPoints: [
      'Dijkstra shortest path algorithm across rural India Post relay nodes: O((V + E) log V)',
      'Dynamic Programming 0/1 Knapsack O(N·W) for courier vehicle weight vs value optimization',
      'Asymptotic time & space complexity analysis (Big-O, Omega, Theta)',
      'Greedy heuristic vs Optimal sub-structure in hub consignment transfers'
    ],
    audioScript: 'Welcome to the Analysis of Algorithms module designed by Vedant Mishra. In this lecture, we examine how Gram AI utilizes Dijkstra shortest-path algorithms to calculate optimal transit routes between village self-help groups and district postal nodal centers. We also model vehicle consignment loading as a 0/1 Knapsack problem where we maximize artisan shipment value subject to courier weight constraints.',
    instructor: 'Vedant Mishra (Lead Systems Engineer)',
    icon: 'Binary'
  },
  {
    id: 'learn-dbms',
    title: 'DBMS: Relational 3NF Schemas, ACID Escrow & B+ Tree Indexing',
    category: 'dbms_database',
    duration: '20 mins',
    language: 'Multilingual (18+ Languages)',
    level: 'Core Engineering',
    summary: 'Explore Gram AI relational database architecture: Entity-Relationship modeling, 3NF normalization, ACID transaction guarantees for UPI escrow, and B+ Tree indexing.',
    keyPoints: [
      'ACID transactional guarantees for NPCI UPI Escrow settlement',
      'Third Normal Form (3NF) schema decomposition preventing insert, update & delete anomalies',
      'B+ Tree clustered and secondary index lookups providing sub-millisecond retrieval latency',
      'Two-Phase Locking (2PL) and Write-Ahead Logging (WAL) for fault-tolerant state recovery'
    ],
    audioScript: 'Welcome to the Database Management Systems lecture by Vedant Mishra. Financial integrity in UPI payments demands strict ACID compliance: Atomicity ensures funds are never lost between bank debits and escrow reserves. We employ Third Normal Form normalization across users, orders, and ledger tables, with B-Plus Tree indices providing sub-millisecond search across rural craft catalogs.',
    instructor: 'Vedant Mishra (Lead Systems Engineer)',
    icon: 'Database'
  },
  {
    id: 'learn-maths',
    title: 'MATHS: Graph Theory, Markov Chains & Demand Forecasting',
    category: 'maths_applied',
    duration: '19 mins',
    language: 'Multilingual (18+ Languages)',
    level: 'Core Engineering',
    summary: 'Applied Discrete Mathematics in commerce: Graph adjacency matrices for logistics networks, Markov state machines for order lifecycle, and linear regression vectors.',
    keyPoints: [
      'Graph Theory: Directed Acyclic Graphs (DAGs) and adjacency matrices for 150k+ relay hubs',
      'Discrete probability & Markov Chain transition matrices for parcel tracking states',
      'Linear algebra & vector dot products for craft recommendation matrices',
      'Combinatorics & recurrence relations in supply chain inventory planning'
    ],
    audioScript: 'Welcome to Applied Mathematics for Systems Engineering by Vedant Mishra. In this module, we model the national rural postal network as a weighted directed graph G equals V, E. Using adjacency matrices, we compute transitive closures and paths. Order fulfillment is formalized as a discrete-time Markov chain with transition states from Placed to In-Transit to Delivered.',
    instructor: 'Vedant Mishra (Lead Systems Engineer)',
    icon: 'Sigma'
  },
  {
    id: 'learn-oop',
    title: 'OOP: SOLID Principles, Design Patterns & Lifecycle Encapsulation',
    category: 'oop_architecture',
    duration: '21 mins',
    language: 'Multilingual (18+ Languages)',
    level: 'Core Engineering',
    summary: 'Software engineering with Object-Oriented Programming: Single Responsibility, Open-Closed principle, Strategy Pattern for payment processors, and State Pattern for order lifecycles.',
    keyPoints: [
      'SOLID design principles applied to clean full-stack TypeScript backend architecture',
      'Strategy Pattern: Polymorphic UpiPaymentStrategy, CardStrategy, and EscrowStrategy',
      'State Pattern: Encapsulated lifecycle transitions for orders and deliveries',
      'Inheritance vs Composition in product catalog hierarchy'
    ],
    audioScript: 'Welcome to Object-Oriented Programming architecture by Vedant Mishra. In Gram AI, maintainability and scalability stem from strict adherence to SOLID principles. The Single Responsibility Principle ensures our payment services remain decoupled from order fulfillment. We implement the Strategy Pattern to dynamically interchange UPI and escrow settlement mechanisms without modifying core order processing classes.',
    instructor: 'Vedant Mishra (Lead Systems Engineer)',
    icon: 'Layers'
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'user-customer-1',
    userName: 'Arjun Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    rating: 5,
    comment: 'The craftsmanship of this Madhubani Tussar silk dupatta is astonishing. The fine line detailing on the border with natural dyes has such depth. Came with a handwritten card from Vedant Mishra and the weavers!',
    date: '2026-09-20',
    verifiedPurchase: true,
    artisanReply: 'Thank you Arjun ji! Knowing that our heritage craft is treasured in Bengaluru brings so much happiness to our artisan guild.'
  },
  {
    id: 'rev-2',
    productId: 'prod-2',
    userId: 'user-customer-2',
    userName: 'Meera Iyer',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    rating: 5,
    comment: 'Cooked biryani in this terracotta handi on gas stove (with heat diffuser). The flavour and aroma were unbeatable. Packaging with dried husk was 100% eco-friendly and arrived intact.',
    date: '2026-09-18',
    verifiedPurchase: true,
    artisanReply: 'Dhanyawad Meera ji. Please remember to soak the pot in clean water for 15 mins before first use. Warm regards from Molela!'
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    userId: 'user-customer-3',
    userName: 'Vikram Sethi',
    userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    rating: 5,
    comment: 'You can immediately tell this Wayanad turmeric is genuinely raw and pure. The intense golden hue and earthy aroma are unlike any commercial brand. 10/10.',
    date: '2026-09-22',
    verifiedPurchase: true
  }
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-1042',
    userId: 'user-artisan-1',
    userName: 'Vedant Mishra',
    role: 'entrepreneur',
    subject: 'Assistance requested for bulk packaging boxes for festive export',
    category: 'logistics',
    status: 'in_progress',
    priority: 'medium',
    createdAt: '2026-09-26T08:30:00Z',
    messages: [
      {
        sender: 'user',
        text: 'Namaste, our craft guild has received 45 orders for Diwali gifting. Can the district hub provide 50 extra corrugated honeycomb sleeves by Monday?',
        time: '08:30 AM'
      },
      {
        sender: 'support',
        text: 'Namaste Vedant ji! Your request has been assigned to Gram Coordinator Suresh. The sleeves will be delivered to your hub tomorrow at 11 AM.',
        time: '09:15 AM'
      }
    ]
  }
];
